# Generated by Django 4.2.7 on 2023-12-06 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('my_key', models.CharField(max_length=50, unique=True, verbose_name='Демо Токен')),
                ('os_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='OS Info')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Info')),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser Info')),
                ('jti', models.CharField(blank=True, max_length=512, null=True, verbose_name='JWT ID')),
                ('ua_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent name')),
                ('ua_model_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent model name')),
                ('ua_os_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent os name')),
                ('ua_os_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent os version')),
                ('ua_browser_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent browser name')),
                ('ua_browser_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent browser version')),
                ('ua_device_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent device type')),
                ('ua_app_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent App type')),
                ('ua_c_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent Country Code')),
                ('user_agent', models.CharField(blank=True, max_length=1024, null=True, verbose_name='User Agent')),
                ('cuser_agent', models.CharField(blank=True, max_length=1024, null=True, verbose_name='CUser Agent')),
                ('is_active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'users_multitoken',
            },
        ),
    ]
