# Generated by Django 4.2.7 on 2023-11-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Разрешенный период',
                'verbose_name_plural': 'Разрешенные периоды',
            },
        ),
        migrations.CreateModel(
            name='AllowedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Разрешенная подписка',
                'verbose_name_plural': 'Разрешенные подписки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('content_id', models.PositiveIntegerField(unique=True)),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_russian', models.BooleanField(default=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allowed_subscriptions', models.ManyToManyField(blank=True, to='internal.allowedsubscription')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='internal.category')),
                ('sponsors', models.ManyToManyField(blank=True, to='internal.sponsor')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контенты',
            },
        ),
    ]
