# Generated by Django 4.2.7 on 2023-11-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedperiod',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='allowedsubscription',
            name='sub_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='ID Подписки'),
        ),
        migrations.AlterField(
            model_name='allowedsubscription',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='allowed_subscriptions',
            field=models.ManyToManyField(blank=True, to='internal.allowedsubscription', verbose_name='Разрешенные подписки'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='broadcast_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID Телеканала'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.broadcastcategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='quality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='broadcastcategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='broadcastcategory',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='broadcastcategory',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на узбекском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на узбекском'),
        ),
        migrations.AlterField(
            model_name='content',
            name='allowed_subscriptions',
            field=models.ManyToManyField(blank=True, to='internal.allowedsubscription', verbose_name='Разрешенные подписки'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='internal.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.PositiveIntegerField(verbose_name='ID Контента'),
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='content',
            name='episode_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода'),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_russian',
            field=models.BooleanField(default=True, verbose_name='На русском'),
        ),
        migrations.AlterField(
            model_name='content',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='internal.sponsor', verbose_name='Спонсоры'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на узбекском'),
        ),
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_chosen',
            field=models.BooleanField(default=False, verbose_name='Выбран'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
