# Generated by Django 4.2.7 on 2023-11-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedPeriod',
        ),
    ]
