# Generated by Django 4.2.7 on 2023-12-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ('-broadcast_id',), 'verbose_name': 'Телеканал', 'verbose_name_plural': '2. Телеканалы'},
        ),
        migrations.AlterModelOptions(
            name='broadcastcategory',
            options={'verbose_name': 'Категория телеканалов', 'verbose_name_plural': '4. Категории телеканалов'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('ordering',), 'verbose_name': 'Категория', 'verbose_name_plural': '3. Категории'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': '1. Контенты'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Спонсор', 'verbose_name_plural': '5. Спонсоры'},
        ),
    ]
