# Generated by Django 4.2.7 on 2023-11-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Категория телеканалов',
                'verbose_name_plural': 'Категории телеканалов',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcast_id', models.PositiveBigIntegerField(unique=True)),
                ('allowed_subscriptions', models.ManyToManyField(blank=True, to='internal.allowedsubscription')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.broadcastcategory')),
            ],
            options={
                'verbose_name': 'Телеканал',
                'verbose_name_plural': 'Телеканалы',
            },
        ),
    ]
