# Generated by Django 4.2.7 on 2023-11-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_delete_allowedperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ('-broadcast_id',), 'verbose_name': 'Телеканал', 'verbose_name_plural': 'Телеканалы'},
        ),
    ]
