# Generated by Django 4.2.7 on 2023-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_broadcastcategory_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='episode_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('content_id', 'episode_id')},
        ),
    ]
