# Generated by Django 4.2.7 on 2023-11-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_category_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='internal.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='sponsors',
            field=models.ManyToManyField(to='internal.sponsor'),
        ),
    ]
