# Generated by Django 4.2.7 on 2023-11-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_alter_content_content_id_alter_content_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='allowed_subscriptions',
            field=models.ManyToManyField(blank=True, to='internal.allowedsubscription'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='internal.category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='internal.sponsor'),
        ),
    ]
