# Generated by Django 4.2.7 on 2023-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_sponsor_is_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedsubscription',
            name='description',
        ),
        migrations.AddField(
            model_name='allowedsubscription',
            name='title',
            field=models.CharField(default='title', max_length=128),
            preserve_default=False,
        ),
    ]
