# Generated by Django 4.2.7 on 2023-11-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
