# Generated by Django 4.2.7 on 2023-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_content_category_content_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
