# Generated by Django 4.2.7 on 2023-11-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_alter_content_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='movie_duration',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
