# Generated by Django 4.2.7 on 2023-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_rename_movie_duration_content_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='episode_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
    ]
