# Generated by Django 4.2.7 on 2023-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_remove_allowedsubscription_sub_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedsubscription',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='allowedsubscription',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='allowedsubscription',
            name='title_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название на узбекском'),
        ),
    ]
