# Generated by Django 4.2.7 on 2023-11-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_rename_title_allowedsubscription_title_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='title',
            new_name='name',
        ),
    ]
