# Generated by Django 4.2.7 on 2023-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0006_alter_content_episode_id_alter_content_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='episode_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
