# Generated by Django 4.2.7 on 2023-11-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_rename_title_sponsor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcastcategory',
            old_name='title_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='broadcastcategory',
            old_name='title_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='broadcastcategory',
            old_name='title_uz',
            new_name='name_uz',
        ),
    ]
