# Generated by Django 4.2.7 on 2023-11-17 05:45

from django.db import migrations
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='2 day'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='2 day'),
        ),
    ]
