# Generated by Django 4.2.7 on 2023-11-21 11:47

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('slug', models.SlugField()),
                ('content_id', models.IntegerField(blank=True, null=True)),
                ('broadcast_id', models.IntegerField(blank=True, null=True)),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=16)),
                ('device', models.CharField(max_length=64)),
                ('duration', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'Истории просмотров',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('sub_id', models.CharField(max_length=8)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
