# Generated by Django 4.2.7 on 2023-11-24 11:59

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('broadcast_id', models.PositiveIntegerField(verbose_name='Телеканал id')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.JSONField(blank=True, default=dict, null=True, verbose_name='Возрастная группа')),
                ('gender', models.JSONField(blank=True, default=dict, null=True, verbose_name='Пол')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Телеканал за день',
                'verbose_name_plural': 'Телеканалы за день',
                'db_table': 'statistic_broadcast_day',
            },
        ),
        migrations.CreateModel(
            name='BroadcastHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('broadcast_id', models.PositiveIntegerField(verbose_name='Телеканал id')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.JSONField(blank=True, default=dict, null=True, verbose_name='Возрастная группа')),
                ('gender', models.JSONField(blank=True, default=dict, null=True, verbose_name='Пол')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Телеканал за час',
                'verbose_name_plural': 'Телеканалы за час',
                'db_table': 'statistic_broadcast_hour',
            },
        ),
        migrations.CreateModel(
            name='BroadcastMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('broadcast_id', models.PositiveIntegerField(verbose_name='Телеканал id')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.JSONField(blank=True, default=dict, null=True, verbose_name='Возрастная группа')),
                ('gender', models.JSONField(blank=True, default=dict, null=True, verbose_name='Пол')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Телеканал за месяц',
                'verbose_name_plural': 'Телеканалы за месяц',
                'db_table': 'statistic_broadcast_month',
            },
        ),
        migrations.CreateModel(
            name='ContentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('content_id', models.PositiveIntegerField(verbose_name='Контент id')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Эпизод id')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.JSONField(blank=True, default=dict, null=True, verbose_name='Возрастная группа')),
                ('gender', models.JSONField(blank=True, default=dict, null=True, verbose_name='Пол')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Контент за день',
                'verbose_name_plural': 'Контенты за день',
                'db_table': 'statistic_content_day',
            },
        ),
        migrations.CreateModel(
            name='ContentHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('content_id', models.PositiveIntegerField(verbose_name='Контент id')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Эпизод id')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.JSONField(blank=True, default=dict, null=True, verbose_name='Возрастная группа')),
                ('gender', models.JSONField(blank=True, default=dict, null=True, verbose_name='Пол')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Контент за час',
                'verbose_name_plural': 'Контенты за час',
                'db_table': 'statistic_content_hour',
            },
        ),
        migrations.CreateModel(
            name='ContentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('content_id', models.PositiveIntegerField(verbose_name='Контент id')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Эпизод id')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.JSONField(blank=True, default=dict, null=True, verbose_name='Возрастная группа')),
                ('gender', models.JSONField(blank=True, default=dict, null=True, verbose_name='Пол')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Контент за месяц',
                'verbose_name_plural': 'Контенты за месяц',
                'db_table': 'statistic_content_month',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('slug', models.SlugField()),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Контент id')),
                ('broadcast_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Телеканал id')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Эпизод id')),
                ('user_agent', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=16, verbose_name='IP адрес')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('age_group', models.PositiveIntegerField(blank=True, choices=[(0, '0-6'), (1, '7-12'), (2, '13-16'), (3, '17-18'), (4, '19-21'), (5, '22-28'), (6, '29-36'), (7, '37-46'), (8, '47-54'), (9, '55+')], null=True, verbose_name='Возрастная группа')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=1, null=True, verbose_name='Пол')),
                ('duration', models.PositiveIntegerField(default=10, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'Истории просмотров',
                'db_table': 'statistic_history',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'db_table': 'statistic_register',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('STARTED', 'В исполнении'), ('FAILURE', 'Ошибка'), ('FINISHED', 'Завершен')], default='PENDING', verbose_name='Статус')),
                ('group', models.CharField(max_length=128, verbose_name='Группа')),
                ('rows_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество строк')),
                ('data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('sub_id', models.CharField(max_length=8, verbose_name='Подписка id')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'db_table': 'statistic_subscription',
            },
        ),
    ]
