# Generated by Django 4.2.7 on 2023-12-02 17:32

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('broadcast_id', models.PositiveIntegerField(verbose_name='ID Телеканала')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Телеканал за день',
                'verbose_name_plural': '08. Телеканалы за день',
                'db_table': 'statistic_broadcast_day',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('broadcast_id', models.PositiveIntegerField(verbose_name='ID Телеканала')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Телеканал за час',
                'verbose_name_plural': '07. Телеканалы за час',
                'db_table': 'statistic_broadcast_hour',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('broadcast_id', models.PositiveIntegerField(verbose_name='ID Телеканала')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Телеканал за месяц',
                'verbose_name_plural': '09. Телеканалы за месяц',
                'db_table': 'statistic_broadcast_month',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='CategoryViewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('category_id', models.PositiveSmallIntegerField(verbose_name='ID Категории')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр категории за день',
                'verbose_name_plural': '11. Просмотры категорий за день',
                'db_table': 'statistic_category_view_day',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='CategoryViewHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('category_id', models.PositiveSmallIntegerField(verbose_name='ID Категории')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр категории за час',
                'verbose_name_plural': '10. Просмотры категорий за час',
                'db_table': 'statistic_category_view_hour',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='CategoryViewMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('category_id', models.PositiveSmallIntegerField(verbose_name='ID Категории')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр категории за месяц',
                'verbose_name_plural': '12. Просмотры категорий за месяц',
                'db_table': 'statistic_category_view_month',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='ContentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID Контента')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Контент за день',
                'verbose_name_plural': '05. Контенты за день',
                'db_table': 'statistic_content_day',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='ContentHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID Контента')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Контент за час',
                'verbose_name_plural': '04. Контенты за час',
                'db_table': 'statistic_content_hour',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='ContentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID Контента')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода')),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
            ],
            options={
                'verbose_name': 'Контент за месяц',
                'verbose_name_plural': '06. Контенты за месяц',
                'db_table': 'statistic_content_month',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('sid', models.CharField(max_length=128, verbose_name='Сессия')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Контента')),
                ('broadcast_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Телеканала')),
                ('episode_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода')),
                ('user_agent', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=16, verbose_name='IP адрес')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('duration', models.PositiveIntegerField(default=10, verbose_name='Длительность')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='2 days', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': '01. Истории просмотров',
                'db_table': 'statistic_history',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': '02. Регистрации',
                'db_table': 'statistic_register',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('CONTENT', 'Контент'), ('BROADCAST', 'Телеканалы'), ('REGISTER', 'Регистрации'), ('SUBSCRIPTIONS', 'Подписки'), ('VISITS', 'Посещения с девайсов'), ('ADS', 'Реклама')], verbose_name='Раздел')),
                ('status', models.CharField(choices=[('GENERATING', 'Генерируется'), ('FAILED', 'Ошибка'), ('FINISHED', 'Завершен')], default='PENDING', verbose_name='Статус')),
                ('additional_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительные данные')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d', verbose_name='Файл')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс генерации')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Скачан ли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': '13. Отчеты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('sub_id', models.CharField(max_length=8, verbose_name='ID Подписки')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': '03. Подписки',
                'db_table': 'statistic_subscription',
                'ordering': ('-time',),
            },
        ),
    ]
