# Generated by Django 4.2.7 on 2023-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',), 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='section',
            field=models.CharField(choices=[('CONTENT', 'Контент'), ('BROADCAST', 'Телеканалы'), ('REGISTER', 'Регистрации'), ('SUBSCRIPTIONS', 'Подписки'), ('VISITS', 'Посещения с девайсов'), ('CATEGORY_VIEWS', 'Просмотры категорий'), ('ADS', 'Реклама')], verbose_name='Раздел'),
        ),
    ]
