# Generated by Django 4.2.7 on 2023-11-22 17:41

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('broadcast_id', models.PositiveIntegerField()),
                ('watched_users_count', models.PositiveIntegerField(default=0)),
                ('watched_duration', models.PositiveIntegerField(default=0)),
                ('age_group', models.JSONField(blank=True, default=dict, null=True)),
                ('gender', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Телеканал за день',
                'verbose_name_plural': 'Телеканалы за день',
                'db_table': 'statistic_broadcast_day',
            },
        ),
        migrations.CreateModel(
            name='BroadcastMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('broadcast_id', models.PositiveIntegerField()),
                ('watched_users_count', models.PositiveIntegerField(default=0)),
                ('watched_duration', models.PositiveIntegerField(default=0)),
                ('age_group', models.JSONField(blank=True, default=dict, null=True)),
                ('gender', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Телеканал за месяц',
                'verbose_name_plural': 'Телеканалы за месяц',
                'db_table': 'statistic_broadcast_month',
            },
        ),
    ]
