# Generated by Django 4.2.7 on 2023-11-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastday',
            name='broadcast_id',
            field=models.PositiveIntegerField(verbose_name='ID Телеканала'),
        ),
        migrations.AlterField(
            model_name='broadcasthour',
            name='broadcast_id',
            field=models.PositiveIntegerField(verbose_name='ID Телеканала'),
        ),
        migrations.AlterField(
            model_name='broadcastmonth',
            name='broadcast_id',
            field=models.PositiveIntegerField(verbose_name='ID Телеканала'),
        ),
        migrations.AlterField(
            model_name='contentday',
            name='content_id',
            field=models.PositiveIntegerField(verbose_name='ID Контента'),
        ),
        migrations.AlterField(
            model_name='contentday',
            name='episode_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода'),
        ),
        migrations.AlterField(
            model_name='contenthour',
            name='content_id',
            field=models.PositiveIntegerField(verbose_name='ID Контента'),
        ),
        migrations.AlterField(
            model_name='contenthour',
            name='episode_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода'),
        ),
        migrations.AlterField(
            model_name='contentmonth',
            name='content_id',
            field=models.PositiveIntegerField(verbose_name='ID Контента'),
        ),
        migrations.AlterField(
            model_name='contentmonth',
            name='episode_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода'),
        ),
        migrations.AlterField(
            model_name='history',
            name='broadcast_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Телеканала'),
        ),
        migrations.AlterField(
            model_name='history',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Контента'),
        ),
        migrations.AlterField(
            model_name='history',
            name='episode_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Эпизода'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.CharField(max_length=8, verbose_name='ID Подписки'),
        ),
    ]
