# Generated by Django 4.2.7 on 2023-11-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcasthour',
            options={'verbose_name': 'Телеканал за час', 'verbose_name_plural': 'Телеканалы за час'},
        ),
    ]
