# Generated by Django 4.2.7 on 2023-12-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyContentTotalView',
            new_name='DailyContentView',
        ),
        migrations.AlterModelTable(
            name='dailycontentview',
            table='statistic_daily_content_view',
        ),
    ]
