# Generated by Django 4.2.7 on 2023-11-28 19:34

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Профиль за день',
                'verbose_name_plural': 'Профили за день',
                'db_table': 'statistic_profile_day',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='ProfileMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Профиль за месяц',
                'verbose_name_plural': 'Профили за месяц',
                'db_table': 'statistic_profile_month',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='ProfileHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day', verbose_name='Создано')),
                ('age_group', models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], verbose_name='Пол')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
                ('device', models.CharField(max_length=64, verbose_name='Устройство')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотров')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='internal.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Профиль за час',
                'verbose_name_plural': 'Профили за час',
                'db_table': 'statistic_profile_hour',
                'ordering': ('-time',),
            },
        ),
    ]
