# Generated by Django 4.2.7 on 2023-11-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_broadcastday_broadcast_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenthour',
            options={'ordering': ('time',), 'verbose_name': 'Контент за час', 'verbose_name_plural': 'Контенты за час'},
        ),
    ]
