# Generated by Django 4.2.7 on 2023-11-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_broadcasthour_watched_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcasthour',
            options={'verbose_name': 'Прямой эфир за час', 'verbose_name_plural': 'Прямые эфиры за час'},
        ),
        migrations.AlterModelOptions(
            name='contenthour',
            options={'verbose_name': 'Контента за час', 'verbose_name_plural': 'Контенты за час'},
        ),
    ]
