# Generated by Django 4.2.7 on 2023-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_broadcasthour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasthour',
            name='age_group',
            field=models.JSONField(blank=True, default={0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}, null=True),
        ),
        migrations.AddField(
            model_name='broadcasthour',
            name='gender',
            field=models.JSONField(blank=True, default={'M': 0, 'W': 0}, null=True),
        ),
    ]
