# Generated by Django 4.2.7 on 2023-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_report_options_alter_report_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('GENERATING', 'Генерируется'), ('FAILED', 'Ошибка'), ('FINISHED', 'Завершен')], default='GENERATING', verbose_name='Статус'),
        ),
    ]
