# Generated by Django 4.2.7 on 2023-11-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_profileday_profilemonth_profilehour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastday',
            name='watched_users_count',
        ),
        migrations.RemoveField(
            model_name='broadcasthour',
            name='watched_users_count',
        ),
        migrations.RemoveField(
            model_name='contentday',
            name='watched_users_count',
        ),
        migrations.RemoveField(
            model_name='contenthour',
            name='watched_users_count',
        ),
        migrations.AddField(
            model_name='report',
            name='is_downloaded',
            field=models.BooleanField(default=False, verbose_name='Скачан ли'),
        ),
        migrations.AddField(
            model_name='report',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс генерации'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('GENERATING', 'Генерируется'), ('FAILED', 'Ошибка'), ('FINISHED', 'Завершен')], default='PENDING', verbose_name='Статус'),
        ),
    ]
