# Generated by Django 4.2.7 on 2023-11-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_broadcastday_broadcastmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('STARTED', 'В исполнении'), ('FAILURE', 'Ошибка'), ('FINISHED', 'Завершен')], default='PENDING')),
                ('section', models.CharField(max_length=128)),
                ('lines_count', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('file', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
