# Generated by Django 4.2.7 on 2023-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryviewhour',
            name='category_id',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ID Категории'),
        ),
    ]
