# Generated by Django 4.2.7 on 2023-12-05 11:16

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_dailyseparatedview_delete_dailycontentview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Посещения с девайсов',
                'verbose_name_plural': '04. Посещения с девайсов',
                'db_table': 'statistic_device_visit',
                'ordering': ('-time',),
            },
        ),
        migrations.AlterModelOptions(
            name='broadcastday',
            options={'ordering': ('-time',), 'verbose_name': 'Телеканал за день', 'verbose_name_plural': '09. Телеканалы за день'},
        ),
        migrations.AlterModelOptions(
            name='broadcasthour',
            options={'ordering': ('-time',), 'verbose_name': 'Телеканал за час', 'verbose_name_plural': '08. Телеканалы за час'},
        ),
        migrations.AlterModelOptions(
            name='broadcastmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Телеканал за месяц', 'verbose_name_plural': '10. Телеканалы за месяц'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewday',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за день', 'verbose_name_plural': '15. Просмотры категорий за день'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewhour',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за час', 'verbose_name_plural': '14. Просмотры категорий за час'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за месяц', 'verbose_name_plural': '16. Просмотры категорий за месяц'},
        ),
        migrations.AlterModelOptions(
            name='contentday',
            options={'ordering': ('-time',), 'verbose_name': 'Контент за день', 'verbose_name_plural': '06. Контенты за день'},
        ),
        migrations.AlterModelOptions(
            name='contenthour',
            options={'ordering': ('time',), 'verbose_name': 'Контент за час', 'verbose_name_plural': '05. Контенты за час'},
        ),
        migrations.AlterModelOptions(
            name='contentmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Контент за месяц', 'verbose_name_plural': '07. Контенты за месяц'},
        ),
        migrations.AlterModelOptions(
            name='dailyseparatedview',
            options={'ordering': ('-time',), 'verbose_name': 'Отдельные просмотры контента', 'verbose_name_plural': '13. Отдельные просмотры контентов'},
        ),
        migrations.AlterModelOptions(
            name='dailytotalview',
            options={'ordering': ('-time',), 'verbose_name': 'Общий просмотр', 'verbose_name_plural': '12. Общие просмотры'},
        ),
    ]
