# Generated by Django 4.2.7 on 2023-11-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_remove_broadcastday_watched_users_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastday',
            name='country',
        ),
        migrations.RemoveField(
            model_name='broadcastday',
            name='device',
        ),
        migrations.RemoveField(
            model_name='broadcasthour',
            name='country',
        ),
        migrations.RemoveField(
            model_name='broadcasthour',
            name='device',
        ),
        migrations.RemoveField(
            model_name='broadcastmonth',
            name='country',
        ),
        migrations.RemoveField(
            model_name='broadcastmonth',
            name='device',
        ),
        migrations.RemoveField(
            model_name='contentday',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contentday',
            name='device',
        ),
        migrations.RemoveField(
            model_name='contenthour',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contenthour',
            name='device',
        ),
        migrations.RemoveField(
            model_name='contentmonth',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contentmonth',
            name='device',
        ),
        migrations.RemoveField(
            model_name='history',
            name='country',
        ),
        migrations.RemoveField(
            model_name='history',
            name='device',
        ),
    ]
