# Generated by Django 4.2.7 on 2023-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_broadcasthour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenthour',
            name='content_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenthour',
            name='episode_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
