# Generated by Django 4.2.7 on 2023-11-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='lines_count',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
