# Generated by Django 4.2.7 on 2023-11-21 16:35

from django.db import migrations, models
import statistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_broadcasthour_age_group_broadcasthour_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasthour',
            name='age_group',
            field=models.JSONField(blank=True, default=statistic.models.get_default_age_group, null=True),
        ),
        migrations.AlterField(
            model_name='broadcasthour',
            name='gender',
            field=models.JSONField(blank=True, default=statistic.models.get_default_gender, null=True),
        ),
        migrations.AlterField(
            model_name='contenthour',
            name='age_group',
            field=models.JSONField(blank=True, default=statistic.models.get_default_age_group, null=True),
        ),
        migrations.AlterField(
            model_name='contenthour',
            name='gender',
            field=models.JSONField(blank=True, default=statistic.models.get_default_gender, null=True),
        ),
    ]
