# Generated by Django 4.2.7 on 2023-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_report_file_alter_report_lines_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
