# Generated by Django 4.2.7 on 2023-11-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_remove_broadcastday_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileDay',
        ),
        migrations.RemoveField(
            model_name='profilehour',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProfileMonth',
        ),
        migrations.AlterModelOptions(
            name='broadcastmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Профиль за месяц', 'verbose_name_plural': 'Профили за месяц'},
        ),
        migrations.AlterModelTable(
            name='broadcastmonth',
            table='statistic_profile_month',
        ),
        migrations.DeleteModel(
            name='ProfileHour',
        ),
    ]
