# Generated by Django 4.2.7 on 2023-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_broadcasthour_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasthour',
            name='watched_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='broadcasthour',
            name='watched_users_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
