# Generated by Django 4.2.7 on 2023-12-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_alter_categoryviewhour_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryviewhour',
            name='category_id',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ID Категории'),
            preserve_default=False,
        ),
    ]
