# Generated by Django 4.2.7 on 2023-11-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_alter_broadcastday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='age_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='history',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
