# Generated by Django 4.2.7 on 2023-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_alter_report_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lines_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
