# Generated by Django 4.2.7 on 2023-11-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_delete_profileday_remove_profilehour_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmonth',
            options={'ordering': ('-broadcast_id',), 'verbose_name': 'Телеканал за месяц', 'verbose_name_plural': 'Телеканалы за месяц'},
        ),
        migrations.AlterModelTable(
            name='broadcastmonth',
            table='statistic_broadcast_month',
        ),
    ]
