# Generated by Django 4.2.7 on 2023-12-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_alter_adsview_options_alter_devicevisit_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailySeparatedView',
            new_name='DailyDetailView',
        ),
        migrations.AlterModelOptions(
            name='dailydetailview',
            options={'ordering': ('-time',), 'verbose_name': 'Детальные просмотры', 'verbose_name_plural': '13. Детальные просмотры'},
        ),
        migrations.AlterModelTable(
            name='dailydetailview',
            table='statistic_daily_detail_view',
        ),
    ]
