# Generated by Django 4.2.7 on 2023-11-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_alter_broadcastmonth_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Телеканал за месяц', 'verbose_name_plural': 'Телеканалы за месяц'},
        ),
    ]
