# Generated by Django 4.2.7 on 2023-11-22 13:28

from django.db import migrations, models
import statistic.models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_alter_broadcasthour_table_alter_contenthour_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('content_id', models.IntegerField()),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('watched_users_count', models.PositiveIntegerField(default=0)),
                ('watched_duration', models.PositiveIntegerField(default=0)),
                ('age_group', models.JSONField(blank=True, default=statistic.models.get_default_age_group, null=True)),
                ('gender', models.JSONField(blank=True, default=statistic.models.get_default_gender, null=True)),
            ],
            options={
                'verbose_name': 'Контент за месяц',
                'verbose_name_plural': 'Контенты за месяц',
                'db_table': 'statistic_content_day',
            },
        ),
        migrations.CreateModel(
            name='ContentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('content_id', models.IntegerField()),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('watched_users_count', models.PositiveIntegerField(default=0)),
                ('watched_duration', models.PositiveIntegerField(default=0)),
                ('age_group', models.JSONField(blank=True, default=statistic.models.get_default_age_group, null=True)),
                ('gender', models.JSONField(blank=True, default=statistic.models.get_default_gender, null=True)),
            ],
            options={
                'verbose_name': 'Контент за месяц',
                'verbose_name_plural': 'Контенты за месяц',
                'db_table': 'statistic_content_month',
            },
        ),
    ]
