# Generated by Django 4.2.7 on 2023-11-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_alter_report_lines_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='section',
            new_name='group',
        ),
    ]
