# Generated by Django 4.2.7 on 2023-11-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_contentday_contentmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentday',
            options={'verbose_name': 'Контент за день', 'verbose_name_plural': 'Контенты за день'},
        ),
    ]
