# Generated by Django 4.2.7 on 2023-12-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_rename_dailyseparatedview_dailydetailview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydetailview',
            name='broadcast_id',
        ),
    ]
