# Generated by Django 4.2.7 on 2023-11-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_broadcastday_age_group_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastday',
            name='age_group_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество возрастной группы'),
        ),
        migrations.AlterField(
            model_name='broadcastday',
            name='gender_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пола'),
        ),
        migrations.AlterField(
            model_name='broadcasthour',
            name='age_group_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество возрастной группы'),
        ),
        migrations.AlterField(
            model_name='broadcasthour',
            name='gender_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пола'),
        ),
        migrations.AlterField(
            model_name='broadcastmonth',
            name='age_group_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество возрастной группы'),
        ),
        migrations.AlterField(
            model_name='broadcastmonth',
            name='gender_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пола'),
        ),
        migrations.AlterField(
            model_name='contentday',
            name='age_group_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество возрастной группы'),
        ),
        migrations.AlterField(
            model_name='contentday',
            name='gender_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пола'),
        ),
        migrations.AlterField(
            model_name='contenthour',
            name='age_group_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество возрастной группы'),
        ),
        migrations.AlterField(
            model_name='contenthour',
            name='gender_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пола'),
        ),
        migrations.AlterField(
            model_name='contentmonth',
            name='age_group_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество возрастной группы'),
        ),
        migrations.AlterField(
            model_name='contentmonth',
            name='gender_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пола'),
        ),
        migrations.AlterField(
            model_name='history',
            name='age_group',
            field=models.CharField(choices=[(0, '0-6'), (1, '7-12'), (2, '13-16'), (3, '17-18'), (4, '19-21'), (5, '22-28'), (6, '29-36'), (7, '37-46'), (8, '47-54'), (9, '55+')], default=1, verbose_name='Возрастная группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], default=1, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
