# Generated by Django 4.2.7 on 2023-12-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_dailytotalview_alter_history_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryviewday',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за день', 'verbose_name_plural': '12. Просмотры категорий за день'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewhour',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за час', 'verbose_name_plural': '11. Просмотры категорий за час'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за месяц', 'verbose_name_plural': '13. Просмотры категорий за месяц'},
        ),
        migrations.AlterModelOptions(
            name='dailytotalview',
            options={'ordering': ('-time',), 'verbose_name': 'Общий просмотр за день', 'verbose_name_plural': '10. Общие просмотры за день'},
        ),
        migrations.AlterModelTable(
            name='dailytotalview',
            table='statistic_daily_total_view',
        ),
    ]
