# Generated by Django 4.2.7 on 2023-12-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_remove_dailydetailview_broadcast_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyDetailView',
            new_name='DailyContentViews',
        ),
        migrations.RenameModel(
            old_name='DailyTotalView',
            new_name='DailyTotalViews',
        ),
        migrations.AlterModelTable(
            name='dailycontentviews',
            table='statistic_daily_content_views',
        ),
        migrations.AlterModelTable(
            name='dailytotalviews',
            table='statistic_daily_total_views',
        ),
    ]
