# Generated by Django 4.2.7 on 2023-12-05 09:41

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_alter_categoryviewday_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContentTotalView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Контента')),
                ('broadcast_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Телеканала')),
                ('category_id', models.PositiveSmallIntegerField(verbose_name='ID Категории')),
                ('watched_users_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'statistic_daily_content_total_view',
                'ordering': ('-time',),
            },
        ),
        migrations.AlterModelOptions(
            name='dailytotalview',
            options={'ordering': ('-time',), 'verbose_name': 'Общий просмотр', 'verbose_name_plural': '10. Общие просмотры'},
        ),
    ]
