# Generated by Django 4.2.7 on 2023-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_alter_broadcastday_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastday',
            name='age_group',
            field=models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='broadcasthour',
            name='age_group',
            field=models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='broadcastmonth',
            name='age_group',
            field=models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='contentday',
            name='age_group',
            field=models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='contenthour',
            name='age_group',
            field=models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='contentmonth',
            name='age_group',
            field=models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='history',
            name='age_group',
            field=models.CharField(choices=[('0', '0-6'), ('1', '7-12'), ('2', '13-15'), ('3', '16-18'), ('4', '19-21'), ('5', '22-28'), ('6', '29-36'), ('7', '37-46'), ('8', '47-54'), ('9', '55+')], verbose_name='Возрастная группа'),
        ),
    ]
