# Generated by Django 4.2.7 on 2023-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_rename_dailydetailview_dailycontentviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycontentviews',
            name='category_id',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ID Категории'),
        ),
    ]
