# Generated by Django 4.2.7 on 2023-11-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0010_alter_broadcastday_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastday',
            name='age_group_count',
        ),
        migrations.RemoveField(
            model_name='broadcastday',
            name='gender_count',
        ),
        migrations.RemoveField(
            model_name='broadcasthour',
            name='age_group_count',
        ),
        migrations.RemoveField(
            model_name='broadcasthour',
            name='gender_count',
        ),
        migrations.RemoveField(
            model_name='broadcastmonth',
            name='age_group_count',
        ),
        migrations.RemoveField(
            model_name='broadcastmonth',
            name='gender_count',
        ),
        migrations.RemoveField(
            model_name='contentday',
            name='age_group_count',
        ),
        migrations.RemoveField(
            model_name='contentday',
            name='gender_count',
        ),
        migrations.RemoveField(
            model_name='contenthour',
            name='age_group_count',
        ),
        migrations.RemoveField(
            model_name='contenthour',
            name='gender_count',
        ),
        migrations.RemoveField(
            model_name='contentmonth',
            name='age_group_count',
        ),
        migrations.RemoveField(
            model_name='contentmonth',
            name='gender_count',
        ),
    ]
