# Generated by Django 4.2.7 on 2023-12-06 14:07

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0010_alter_dailycontentviews_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Регистрации в час',
                'verbose_name_plural': '02. Регистрации в часы',
                'db_table': 'statistic_register_hour',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='3 month', verbose_name='Создано')),
                ('sub_id', models.CharField(max_length=8, verbose_name='ID Подписки')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Подписки в час',
                'verbose_name_plural': '03. Подписки в часы',
                'db_table': 'statistic_subscription_hour',
                'ordering': ('-time',),
            },
        ),
        migrations.RenameModel(
            old_name='Register',
            new_name='RegisterDay',
        ),
        migrations.RenameModel(
            old_name='Subscription',
            new_name='SubscriptionDay',
        ),
        migrations.AlterModelOptions(
            name='registerday',
            options={'ordering': ('-time',), 'verbose_name': 'Регистрации в день', 'verbose_name_plural': '02. Регистрации в дни'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionday',
            options={'ordering': ('-time',), 'verbose_name': 'Подписки в день', 'verbose_name_plural': '03. Подписки в дни'},
        ),
        migrations.AlterModelTable(
            name='registerday',
            table='statistic_register_day',
        ),
    ]
