# Generated by Django 4.2.7 on 2023-12-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0011_registerhour_subscriptionhour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerday',
            options={'ordering': ('-time',), 'verbose_name': 'Регистрации в день', 'verbose_name_plural': '03. Регистрации в дни'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionday',
            options={'ordering': ('-time',), 'verbose_name': 'Подписки в день', 'verbose_name_plural': '05. Подписки в дни'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionhour',
            options={'ordering': ('-time',), 'verbose_name': 'Подписки в час', 'verbose_name_plural': '04. Подписки в часы'},
        ),
        migrations.AlterModelTable(
            name='subscriptionday',
            table='statistic_subscription_day',
        ),
    ]
