# Generated by Django 4.2.7 on 2023-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0013_alter_adsview_options_alter_broadcastday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsview',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр рекламы', 'verbose_name_plural': '15. Просмотры реклам'},
        ),
        migrations.AlterModelOptions(
            name='dailycontentviews',
            options={'ordering': ('-time',), 'verbose_name': 'Детальные просмотры', 'verbose_name_plural': '14. Детальные просмотры'},
        ),
        migrations.AlterModelOptions(
            name='dailytotalviews',
            options={'ordering': ('-time',), 'verbose_name': 'Общий просмотр', 'verbose_name_plural': '13. Общие просмотры'},
        ),
    ]
