# Generated by Django 4.2.7 on 2023-12-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_alter_adsview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevisit',
            name='app_type',
            field=models.CharField(choices=[('app', 'app'), ('tv', 'tv'), ('web', 'web')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicevisit',
            name='country',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicevisit',
            name='device_type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('SmartTV', 'SmartTV'), ('Desktop', 'Desktop')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicevisit',
            name='os_type',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Linux', 'Linux'), ('Tizen', 'Tizen'), ('Web0S', 'Web0S'), ('Mac OS X', 'Mac OS X'), ('Chrome OS', 'Chrome OS'), ('FreeBSD', 'FreeBSD'), ('Ubuntu', 'Ubuntu')], default=1),
            preserve_default=False,
        ),
    ]
