# Generated by Django 4.2.7 on 2023-12-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0016_devicevisithour_devicevisitmonth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsview',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр рекламы', 'verbose_name_plural': '17. Просмотры реклам'},
        ),
        migrations.AlterModelOptions(
            name='broadcastday',
            options={'ordering': ('-time',), 'verbose_name': 'Телеканал за день', 'verbose_name_plural': '13. Телеканалы за день'},
        ),
        migrations.AlterModelOptions(
            name='broadcasthour',
            options={'ordering': ('-time',), 'verbose_name': 'Телеканал за час', 'verbose_name_plural': '12. Телеканалы за час'},
        ),
        migrations.AlterModelOptions(
            name='broadcastmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Телеканал за месяц', 'verbose_name_plural': '14. Телеканалы за месяц'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewday',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за день', 'verbose_name_plural': '19. Просмотры категорий за день'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewhour',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за час', 'verbose_name_plural': '18. Просмотры категорий за час'},
        ),
        migrations.AlterModelOptions(
            name='categoryviewmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Просмотр категории за месяц', 'verbose_name_plural': '20. Просмотры категорий за месяц'},
        ),
        migrations.AlterModelOptions(
            name='contentday',
            options={'ordering': ('-time',), 'verbose_name': 'Контент за день', 'verbose_name_plural': '10. Контенты за день'},
        ),
        migrations.AlterModelOptions(
            name='contenthour',
            options={'ordering': ('time',), 'verbose_name': 'Контент за час', 'verbose_name_plural': '09. Контенты за час'},
        ),
        migrations.AlterModelOptions(
            name='contentmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Контент за месяц', 'verbose_name_plural': '11. Контенты за месяц'},
        ),
        migrations.AlterModelOptions(
            name='dailycontentviews',
            options={'ordering': ('-time',), 'verbose_name': 'Детальные просмотры', 'verbose_name_plural': '16. Детальные просмотры'},
        ),
        migrations.AlterModelOptions(
            name='dailytotalviews',
            options={'ordering': ('-time',), 'verbose_name': 'Общий просмотр', 'verbose_name_plural': '15. Общие просмотры'},
        ),
    ]
