# Generated by Django 4.2.7 on 2023-12-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0017_alter_adsview_options_alter_broadcastday_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceVisitMonth',
            new_name='DeviceVisitsDay',
        ),
        migrations.RenameModel(
            old_name='DeviceVisitHour',
            new_name='DeviceVisitsHour',
        ),
        migrations.RenameModel(
            old_name='DeviceVisitDay',
            new_name='DeviceVisitsMonth',
        ),
        migrations.AlterModelOptions(
            name='devicevisitsday',
            options={'ordering': ('-time',), 'verbose_name': 'Посещения с девайсов день', 'verbose_name_plural': '07. Посещения с девайсов за день'},
        ),
        migrations.AlterModelOptions(
            name='devicevisitsmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Посещения с девайсов за месяц', 'verbose_name_plural': '08. Посещения с девайсов за месяц'},
        ),
        migrations.AlterModelTable(
            name='devicevisitsday',
            table='statistic_device_visits_day',
        ),
        migrations.AlterModelTable(
            name='devicevisitshour',
            table='statistic_device_visits_hour',
        ),
        migrations.AlterModelTable(
            name='devicevisitsmonth',
            table='statistic_device_visits_month',
        ),
    ]
