# Generated by Django 4.2.7 on 2023-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0018_rename_devicevisitmonth_devicevisitsday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevisitsday',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='devicevisitshour',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='devicevisitsmonth',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='devicevisitsday',
            name='app_type',
            field=models.CharField(choices=[('app', 'app'), ('tv', 'tv'), ('web', 'web')], verbose_name='Вход из'),
        ),
        migrations.AlterField(
            model_name='devicevisitsday',
            name='country',
            field=models.CharField(max_length=32, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='devicevisitsday',
            name='device_type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('SmartTV', 'SmartTV'), ('Desktop', 'Desktop')], verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='devicevisitsday',
            name='os_type',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Linux', 'Linux'), ('Tizen', 'Tizen'), ('Web0S', 'Web0S'), ('Mac OS X', 'Mac OS X'), ('Chrome OS', 'Chrome OS'), ('FreeBSD', 'FreeBSD'), ('Ubuntu', 'Ubuntu')], verbose_name='Тип OC'),
        ),
        migrations.AlterField(
            model_name='devicevisitshour',
            name='app_type',
            field=models.CharField(choices=[('app', 'app'), ('tv', 'tv'), ('web', 'web')], verbose_name='Вход из'),
        ),
        migrations.AlterField(
            model_name='devicevisitshour',
            name='country',
            field=models.CharField(max_length=32, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='devicevisitshour',
            name='device_type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('SmartTV', 'SmartTV'), ('Desktop', 'Desktop')], verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='devicevisitshour',
            name='os_type',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Linux', 'Linux'), ('Tizen', 'Tizen'), ('Web0S', 'Web0S'), ('Mac OS X', 'Mac OS X'), ('Chrome OS', 'Chrome OS'), ('FreeBSD', 'FreeBSD'), ('Ubuntu', 'Ubuntu')], verbose_name='Тип OC'),
        ),
        migrations.AlterField(
            model_name='devicevisitsmonth',
            name='app_type',
            field=models.CharField(choices=[('app', 'app'), ('tv', 'tv'), ('web', 'web')], verbose_name='Вход из'),
        ),
        migrations.AlterField(
            model_name='devicevisitsmonth',
            name='country',
            field=models.CharField(max_length=32, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='devicevisitsmonth',
            name='device_type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('SmartTV', 'SmartTV'), ('Desktop', 'Desktop')], verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='devicevisitsmonth',
            name='os_type',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Linux', 'Linux'), ('Tizen', 'Tizen'), ('Web0S', 'Web0S'), ('Mac OS X', 'Mac OS X'), ('Chrome OS', 'Chrome OS'), ('FreeBSD', 'FreeBSD'), ('Ubuntu', 'Ubuntu')], verbose_name='Тип OC'),
        ),
    ]
