# Generated by Django 4.2.7 on 2023-12-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0019_devicevisitsday_count_devicevisitshour_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicevisitsday',
            options={'ordering': ('-time',), 'verbose_name': 'Посещения с устройств за день', 'verbose_name_plural': '07. Посещения с устройств за день'},
        ),
        migrations.AlterModelOptions(
            name='devicevisitshour',
            options={'ordering': ('-time',), 'verbose_name': 'Посещения с устройства за час', 'verbose_name_plural': '06. Посещения с устройств за час'},
        ),
        migrations.AlterModelOptions(
            name='devicevisitsmonth',
            options={'ordering': ('-time',), 'verbose_name': 'Посещения с устройства за месяц', 'verbose_name_plural': '08. Посещения с устройств за месяц'},
        ),
    ]
