# Generated by Django 4.2.7 on 2023-12-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0020_alter_devicevisitsday_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerday',
            options={'ordering': ('-time',), 'verbose_name': 'Регистрации за день', 'verbose_name_plural': '03. Регистрации за день'},
        ),
        migrations.AlterModelOptions(
            name='registerhour',
            options={'ordering': ('-time',), 'verbose_name': 'Регистрации за час', 'verbose_name_plural': '02. Регистрации за час'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionday',
            options={'ordering': ('-time',), 'verbose_name': 'Подписки за день', 'verbose_name_plural': '05. Подписки за день'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionhour',
            options={'ordering': ('-time',), 'verbose_name': 'Подписки за час', 'verbose_name_plural': '04. Подписки за час'},
        ),
    ]
